import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgAtomsTabsComponent } from '../../../components/tabs';
import { NgAtomsTabListDirective } from '../../../components/tabs';
import { NgAtomsTabTriggerDirective } from '../../../components/tabs';
import { NgAtomsTabPanelDirective } from '../../../components/tabs';
import { CodeBlockComponent } from '../../../components/code-block/code-block.component';
import {TocComponent} from "../../../components/toc/toc.component";

export interface ComponentEntry {
  name: string;
  route?: string;
  description: string;
  status: 'alpha' | 'stable' | 'planned';
}

@Component({
  selector: 'app-get-started-page',
  standalone: true,
  imports: [
    RouterLink,
    NgAtomsTabsComponent,
    NgAtomsTabListDirective,
    NgAtomsTabTriggerDirective,
    NgAtomsTabPanelDirective,
    CodeBlockComponent,
    TocComponent,
  ],
  templateUrl: './get-started-page.component.html',
  styleUrl: './get-started-page.component.css',
})
export class GetStartedPageComponent {

  readonly pmTabs = [
    { label: 'npm',  code: 'npm install -g ngatoms' },
    { label: 'pnpm', code: 'pnpm add -g ngatoms' },
    { label: 'yarn', code: 'yarn global add ngatoms' },
    { label: 'bun',  code: 'bun add -g ngatoms' },
  ];

  /* Real ngatoms init interactive session */
  readonly initOutput =
`$ ngatoms init

  ? Where should components be copied? (src/components)
  ? Which styles file should imports be added to? (src/styles.css)
  ? Create a theme template? (Y/n) Y

  ✓ Created ngatoms.json
  ✓ Created src/themes/default.css
  ✓ Updated src/styles.css

  Run 'npx ngatoms add button' to add your first component.`;

  /* Real ngatoms add output */
  readonly addOutput =
`$ ngatoms add button

  ✓ Added button to src/components/button/
  ✓ Updated src/styles.css`;

  /* Real import using NgAtomsButtonDirective */
  readonly importCode =
`import { Component } from '@angular/core';
import { NgAtomsButtonDirective } from './components/button';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [NgAtomsButtonDirective],
  template: \`
    <button ngAtomsButton variant="primary">
      Ship it
    </button>
  \`,
})
export class AppComponent {}`;

  readonly themeCode =
`/* src/themes/default.css — generated by ngatoms init. Edit freely. */

:root {
  --nga-color-accent:      #F06B00;
  --nga-color-background:  #FAF8F5;
  --nga-color-foreground:  #1A1714;
  --nga-color-border:      #DED4C5;
  --nga-radius-md:         6px;
  --nga-font-sans:         'Inter', system-ui, sans-serif;
}

.dark {
  --nga-color-background:  #0E0C0A;
  --nga-color-foreground:  #F3EEE7;
  --nga-color-border:      #2A2520;
}`;

  readonly components: ComponentEntry[] = [
    { name: 'accordion',      route: '/accordion',      description: 'Collapsible items with single or multiple open modes.',                         status: 'alpha' },
    { name: 'alert',          route: '/alert',          description: 'Feedback messages — 5 variants: default, info, success, warning, destructive.', status: 'alpha' },
    { name: 'avatar',         route: '/avatar',         description: 'User avatar with image, initials fallback, and icon fallback. 4 sizes.',         status: 'alpha' },
    { name: 'badge',          route: '/badge',          description: 'Labels — 5 variants: default, secondary, outline, destructive, success.',        status: 'alpha' },
    { name: 'button',         route: '/button',         description: '5 variants, 5 sizes, loading state, and icon support.',                          status: 'alpha' },
    { name: 'card',           route: '/card',           description: 'Container with header, title, description, content, and footer slots.',          status: 'alpha' },
    { name: 'checkbox',       route: '/checkbox',       description: 'Checked, unchecked, and indeterminate states.',                                   status: 'alpha' },
    { name: 'date-picker',    route: '/date-picker',    description: 'Custom calendar overlay — single/range, min/max, month/year picker, i18n.',       status: 'alpha' },
    { name: 'dialog',         route: '/dialog',         description: 'Modal using native <dialog>, focus trap, backdrop, and size variants.',           status: 'alpha' },
    { name: 'dropdown-menu',  route: '/dropdown-menu',  description: 'Contextual action menu — 4 placements, flip, icons, keyboard navigation.',        status: 'alpha' },
    { name: 'input',          route: '/input',          description: '3 variants, 5 sizes, invalid state.',                                            status: 'alpha' },
    { name: 'number-input',   route: '/number-input',   description: 'Numeric input with increment/decrement controls, min/max clamping, step.',        status: 'alpha' },
    { name: 'popover',        route: '/popover',        description: 'Floating panel anchored to a trigger — 4 placements, outside-click dismiss.',    status: 'alpha' },
    { name: 'progress',       route: '/progress',       description: 'Progress bar — determinate and indeterminate modes, 3 sizes.',                   status: 'alpha' },
    { name: 'radio-group',    route: '/radio-group',    description: 'Radio button group with keyboard navigation, ARIA support, and 3 sizes.',         status: 'alpha' },
    { name: 'select',         route: '/select',         description: 'Styled native select — 3 variants, 5 sizes.',                                    status: 'alpha' },
    { name: 'separator',      route: '/separator',      description: 'Horizontal or vertical visual divider.',                                          status: 'alpha' },
    { name: 'spinner',        route: '/spinner',        description: 'Loading spinner — 3 sizes.',                                                     status: 'alpha' },
    { name: 'switch',         route: '/switch',         description: 'Toggle switch for enabling/disabling a setting — 3 sizes.',                       status: 'alpha' },
    { name: 'tabs',           route: '/tabs',           description: 'Underline and pills variants, keyboard navigation, and ARIA support.',            status: 'alpha' },
    { name: 'textarea',       route: '/textarea',       description: 'Multiline input with variants, sizes, invalid state, and auto-resize.',           status: 'alpha' },
    { name: 'tooltip',        route: '/tooltip',        description: 'Floating label — 4 placements, delay, and viewport clamping.',                   status: 'alpha' },
    /* Planned */
    { name: 'breadcrumb',     description: 'Hierarchical navigation trail.',                    status: 'planned' },
    { name: 'combobox',       description: 'Text input with filtered dropdown.',                status: 'planned' },
    { name: 'context-menu',   description: 'Right-click triggered menu.',                       status: 'planned' },
    { name: 'drawer',         description: 'Side-panel overlay.',                               status: 'planned' },
    { name: 'file-upload',    description: 'Drag-and-drop file input zone.',                    status: 'planned' },
    { name: 'pagination',     description: 'Page navigation controls.',                         status: 'planned' },
    { name: 'skeleton',       description: 'Placeholder loading shimmer.',                      status: 'planned' },
    { name: 'slider',         description: 'Range slider — single and dual thumb.',             status: 'planned' },
    { name: 'stepper',        description: 'Multi-step wizard progress indicator.',             status: 'planned' },
    { name: 'tag-input',      description: 'Input that creates removable tag chips.',           status: 'planned' },
  ];

  readonly tocItems = [
    { id: 'install',    label: '1 · Install' },
    { id: 'init',       label: '2 · Init' },
    { id: 'add',        label: '3 · Add a component' },
    { id: 'use',        label: '4 · Use it' },
    { id: 'done',       label: '5 · Done' },
    { id: 'theme',      label: 'Theming' },
    { id: 'components', label: 'Components' },
  ];

}
